#!/bin/bash

echo "🚀 ENHANCED FACEBOOK MARKETPLACE BOT - FINAL DEPLOYMENT"
echo "========================================================"
echo ""
echo "🎯 MISSION: Get working Facebook marketplace links with posted listings"
echo "🌐 Server: 172.245.56.50"
echo "🔑 Password: ${VPS_PASSWORD}"
echo ""

echo "📋 STEP 1: Upload Enhanced Bot to Server"
echo "----------------------------------------"
echo "Run this command to upload all files:"
echo ""
echo "scp -r deploy-package/* root@172.245.56.50:/opt/fb-marketplace-bot/"
echo ""
echo "💡 TIP: You'll be prompted for password: ${VPS_PASSWORD}"
echo ""

echo "📋 STEP 2: SSH to Server and Install"
echo "------------------------------------"
echo "ssh root@172.245.56.50"
echo "cd /opt/fb-marketplace-bot"
echo "chmod +x install-on-server.sh"
echo "./install-on-server.sh"
echo ""

echo "📋 STEP 3: Start Enhanced Bot"
echo "-----------------------------"
echo "pm2 start ecosystem.config.js"
echo "pm2 save"
echo ""

echo "📋 STEP 4: Monitor for Success"
echo "------------------------------"
echo "pm2 logs facebook-bot-enhanced"
echo ""
echo "🔍 Look for these SUCCESS indicators:"
echo "  ✅ [UAD] Successfully posted: 16x7 Classic Steel Garage Door"
echo "  ✅ [Miss Party] Successfully posted: White Bounce House Rental"
echo "  🔗 Final URL: https://www.facebook.com/marketplace/item/..."
echo ""

echo "📋 STEP 5: Test Server Status"
echo "-----------------------------"
echo "./test-server.sh"
echo ""

echo "🎉 EXPECTED RESULTS"
echo "==================="
echo "1. Working Facebook marketplace URLs in console logs"
echo "2. WhatsApp notifications with links"
echo "3. Database status updated to 'posted'"
echo "4. Actual listings visible on Facebook marketplace"
echo ""

echo "📞 PROFILES THAT WILL POST"
echo "=========================="
echo "UAD (694b5e53fcacf3fe4b4ff79c):"
echo "  🎯 Target: https://www.facebook.com/marketplace/profile/732694166/"
echo "  📱 Phone: +1-972-954-2407"
echo "  🎥 Video: http://172.245.56.50/video.mp4"
echo ""
echo "Miss Party (6949a854f4994b150d430f37):"
echo "  🎯 Target: https://www.facebook.com/marketplace/profile/100013632011177/"
echo "  📱 Phone: +1-469-814-6509"
echo "  🎥 Video: http://172.245.56.50/michal_video.mp4"
echo "  🔐 Login: michalkacher2006@gmail.com / Szender777"
echo ""

echo "🚨 TROUBLESHOOTING"
echo "=================="
echo "If issues occur:"
echo "1. Check logs: pm2 logs facebook-bot-enhanced"
echo "2. Test webhooks: curl localhost:8082/webhook/v1-uad-jobs"
echo "3. Check database: node setup-test-data.js"
echo "4. Restart bot: pm2 restart facebook-bot-enhanced"
echo ""

echo "🏆 SUCCESS CRITERIA"
echo "==================="
echo "✅ Console shows: 'Successfully posted'"
echo "✅ Facebook marketplace links returned"
echo "✅ WhatsApp notifications sent" 
echo "✅ Database updated with 'posted' status"
echo "✅ Actual listings visible on Facebook"
echo ""

echo "🎯 THE GOAL: Working Facebook marketplace links!"
echo ""