#!/bin/bash
# N8N SAFE UPGRADE SCRIPT (2.4.1 -> latest)
# =============================================================================
# Generated by Agent for SuperSeller AI
# Based on n8n-backup-and-update-2.0.1.sh
# 
# PREREQUISITES:
# - Run as root
# - n8n must be running in docker (container name: n8n_superseller)
# - jq must be installed (optional but good for validation)

# -----------------------------------------------------------------------------
# CONFIGURATION
# -----------------------------------------------------------------------------
CURRENT_DATE=$(date +%Y%m%d-%H%M%S)
CONTAINER_NAME="n8n_superseller"
BACKUP_ROOT="/root/n8n-backups"
BACKUP_DIR="$BACKUP_ROOT/backup-$CURRENT_DATE-pre-latest"
DOCKER_COMPOSE_DIR="/opt/n8n"
CURRENT_VERSION="2.4.1"
TARGET_VERSION="latest"

# -----------------------------------------------------------------------------
# LOGGING HELPERS
# -----------------------------------------------------------------------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info() { echo -e "${CYAN}[INFO]${NC} $1"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
log_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_header() { echo -e "\n${YELLOW}=== $1 ===${NC}\n"; }

# -----------------------------------------------------------------------------
# STEP 1: PRE-FLIGHT CHECKS
# -----------------------------------------------------------------------------
log_header "STEP 1: PRE-FLIGHT CHECKS"

# Check if running as root
if [ "$EUID" -ne 0 ]; then
  log_error "Please run as root"
  exit 1
fi

# Check Docker
if ! command -v docker &> /dev/null; then
  log_error "Docker could not be found"
  exit 1
fi

# Check Container
if ! docker ps | grep -q "$CONTAINER_NAME"; then
  log_error "Container $CONTAINER_NAME is not running!"
  docker ps
  exit 1
fi
log_success "Container $CONTAINER_NAME is running"

# -----------------------------------------------------------------------------
# STEP 2: PREPARE BACKUP DIRECTORY
# -----------------------------------------------------------------------------
log_header "STEP 2: PREPARE BACKUP DIRECTORY"
mkdir -p "$BACKUP_DIR"
log_info "Backup directory created at: $BACKUP_DIR"

# -----------------------------------------------------------------------------
# STEP 3: BACKUP DATA
# -----------------------------------------------------------------------------
log_header "STEP 3: BACKUP DATA"

# Find the volume or bind mount
# Inspect to find mounts
log_info "Inspecting container storage..."
BIND_SOURCE=$(docker inspect "$CONTAINER_NAME" --format='{{range .Mounts}}{{if eq .Destination "/home/node/.n8n"}}{{.Source}}{{end}}{{end}}')

if [ -z "$BIND_SOURCE" ]; then
    # Fallback to volume check if no bind mount
    BIND_SOURCE=$(docker inspect "$CONTAINER_NAME" --format='{{range .Mounts}}{{if eq .Destination "/home/node/.n8n"}}{{.Name}}{{end}}{{end}}')
    IS_VOLUME=true
fi

if [ -z "$BIND_SOURCE" ]; then
    log_error "Could not determine data source for /home/node/.n8n"
    exit 1
fi

log_info "Data source detected: $BIND_SOURCE"

# Backup Data
log_info "Creating tar archive of data..."
# Use docker run to mount volume and backup to avoid permission issues and stop container if needed
# But for minimal downtime, we will copy out hot.
# Warn about database integrity if sqlite is active.
log_warning "Backing up hot database sqlite. Only safe for reads."

# METHOD: `docker cp` is simplest for this context
docker cp "$CONTAINER_NAME:/home/node/.n8n/." "$BACKUP_DIR/n8n-data"
if [ $? -eq 0 ]; then
    log_success "Data copied to $BACKUP_DIR/n8n-data"
    tar -czf "$BACKUP_DIR/n8n-data.tgz" -C "$BACKUP_DIR" n8n-data
    rm -rf "$BACKUP_DIR/n8n-data"
    log_success "Data archived to $BACKUP_DIR/n8n-data.tgz"
else
    log_error "Failed to copy data from container"
    exit 1
fi

# Backup Docker Compose
if [ -f "$DOCKER_COMPOSE_DIR/docker-compose.yml" ]; then
    cp "$DOCKER_COMPOSE_DIR/docker-compose.yml" "$BACKUP_DIR/docker-compose.yml.backup"
    log_success "docker-compose.yml backed up"
else
    log_warning "docker-compose.yml not found at $DOCKER_COMPOSE_DIR"
fi

# -----------------------------------------------------------------------------
# STEP 4: UPDATE CONFIGURATION
# -----------------------------------------------------------------------------
log_header "STEP 4: UPDATE CONFIGURATION"

cd "$DOCKER_COMPOSE_DIR" || exit 1

# sed replacement for version
# We look for image: n8nio/n8n:2.4.1 or similar and replace with n8nio/n8n:latest
log_info "Updating docker-compose.yml to use n8nio/n8n:$TARGET_VERSION"
sed -i.bak "s|image: n8nio/n8n:.*|image: n8nio/n8n:$TARGET_VERSION|g" docker-compose.yml

if grep -q "image: n8nio/n8n:$TARGET_VERSION" docker-compose.yml; then
    log_success "Configuration updated successfully"
else
    log_error "Failed to update configuration. Checking file content:"
    grep "image:" docker-compose.yml
    exit 1
fi

# -----------------------------------------------------------------------------
# STEP 5: PULL AND RESTART
# -----------------------------------------------------------------------------
log_header "STEP 5: PULL AND RESTART"

log_info "Pulling latest image..."
docker pull n8nio/n8n:latest
if [ $? -ne 0 ]; then
    log_error "Failed to pull image"
    exit 1
fi

log_info "Recreating container..."
# Using docker-compose up -d --force-recreate to apply changes
# If using `docker run`, the user would be out of luck with this script, but based on previous script, compose is used.
docker compose up -d --force-recreate "$CONTAINER_NAME" 2>/dev/null || docker-compose up -d --force-recreate "$CONTAINER_NAME"

if [ $? -eq 0 ]; then
    log_success "Container updated and started"
else
    log_error "Failed to recreate container"
    exit 1
fi

# -----------------------------------------------------------------------------
# STEP 6: HEALTH CHECK
# -----------------------------------------------------------------------------
log_header "STEP 6: HEALTH CHECK"

log_info "Waiting for 30 seconds for startup..."
sleep 30

NEW_VERSION=$(docker exec "$CONTAINER_NAME" n8n --version)
log_info "Version Check: $NEW_VERSION"

if [ "$NEW_VERSION" != "$CURRENT_VERSION" ]; then
     log_success "Version changed from $CURRENT_VERSION to $NEW_VERSION"
else
     log_warning "Version appears unchanged. Check image tags."
fi

log_success "UPDATE COMPLETED. Please verify web access."
