name: test
on:
  pull_request:
    paths:
      - "apps/gateway-worker/**"
      - ".github/workflows/test.yaml"
jobs:
  typecheck-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with: { version: 9 }
      - name: Install
        run: pnpm i --frozen-lockfile
      - name: Typecheck
        working-directory: apps/gateway-worker
        run: pnpm typecheck
      - name: Unit tests
        working-directory: apps/gateway-worker
        run: pnpm test